### ISSUE TITLE
dotplot JS function

### ISSUE THREAD

**Issue by martin-raden** [zaidurrehman/RNA-Playground#3]
## general
- [x] keep is simple.. ;)
- [x] add function documentation

## input
- [x] id of element to write to
- [x] RNA sequence (letters ACGUN)
- [x] probability matrix (dimensions = sequence.length, entries in [0,1] or NA value)
- [x] optional: function to call to provide hover content for a cell (with 2 parameters `i,j` for cell selection information) - provide default function that prints cell coordinates i,j and the cell entry = hover_cell_function
- [x] optional: function to call on cell selection (with 2 parameters `i,j` for cell selection information) = select_cell_function

## output
- [x] dotplot
- [x] sequence annotation at borders (use additional row/col with cells same size as dotplot cells)
- [x] zoom/scale via d3 to fit into the div element (max dim = min(div.width,div.height))
- [x] resize "canvas"-div to quadratic min(div.width,div.height)^2
- [x] enable zoom via mouse wheel
- [x] double-click restores initial zoom
- [x] enable dragging (if zoomed in)
- [x] hover information on dotplot cell using the provided hover_cell_function (see input)
- [x] trigger "click_cell_function" on cell selection

## facility methods
- [x] hover tooltip cell information
- [x] highlight row header subsequence for given (i,j) (set background color of rectangle)
- [x] highlight row header cells i and j and draw arc between centers

**Comment by zaidurrehman** [comment]
All done.
